<a href="https://colab.research.google.com/github/samiur06/Machine-Learning-Fall-2022/blob/main/CNN_prob3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Compute the following: 
1. What are the dimensions of the input and the kernel (or filter)? How many parameters 
are there in the kernel f? [2 points] 
2. What is the output activation map when you apply the convolutional operation using the 
filter f on the input X without padding? [4 points] 
3. What is the output when you apply a max-pooling operation on the output from the 
previous question? [4 points] 

In [ ]:
import numpy as np

X = np.array([
    [7,5,0,0,3,2],
    [6,4,5,1,4,8],
    [9,0,2,2,5,4],
    [6,3,4,7,9,8],
    [5,7,5,6,9,0],
    [7,9,0,8,2,3]
    ])

y= np.array([
    [1,0,-1],
    [2,0,-2],
    [1,0,-1],    
    ])

### 3.1 answer:

The dimensions of the input and the kernel are 6x6 and 3x3. There are 3x3 = 9 parameters in the kernel. (The bias term has to be added seperately, it is not in the kernel)

In [ ]:
op1 = np.zeros(16).reshape(4,4)
for i in range(4):
    for j in range(4):
        k = i+3
        l = j+3
        op1[i,j] = (np.sum(X[i:k,j:l] * y))

print(op1)

[[ 16.   9.  -4. -18.]
 [ 17.  -5. -10. -12.]
 [ 11.  -9. -17.   2.]
 [  9.  -1. -15.  16.]]


### 3.2 answer:

This is the output activation map without padding. 

In [ ]:
import skimage.measure

op2 = skimage.measure.block_reduce(op1, (2,2), np.max)
print(op2)

[[17. -4.]
 [11. 16.]]


### 3.3 answer:

This is the output when we apply max-pooling operation on the previous output.